using Content.Client.Guidebook;
using Content.Client.Guidebook.RichText;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Funkystation.UserInterface.Accessability;

[GenerateTypedNameReferences]
public sealed partial class ContentWarningControl : BoxContainer
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;

    public ContentWarningControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var coreEntry = UserInterfaceManager.GetUIController<ContentWarningUIController>().GetContentWarningEntry();
        ProtoId<GuideEntryPrototype>? entry = null;
        entry ??= coreEntry;

        WarningContainer.Children.Clear();
        if (!_parsingMan.TryAddMarkup(WarningContainer, entry.Value))
            return;
    }
}
